{{- if .Values.serviceAccount.create }}
{{- $ctx := dict "helm" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ tpl (.Values.serviceAccount.name | default (include "vmestimator.fullname" (dict "root" .))) . }}
  namespace: {{ include "vm.namespace" $ctx }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
{{- end }}
