#
# Use this file instead of Makefile to use rootless podman containers instead of docker:
#
#   make -f Makefile.podman ...
#
DOCKER = podman
DOCKER_USER_OPTION =
DOCKER_VOLUME_OPTION_SUFFIX = :z

include Makefile
