{{- $app := .Values.alertmanager }}
{{- if and $app.enabled (empty $app.configMap) (empty $app.configSecret) (not (include "vm.operator.enabled" .)) }}
{{- $ctx := dict "helm" . "appKey" "alertmanager" "kindOverride" "vmalertmanager" }}
{{- $ns := include "vm.namespace" $ctx }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager.config.name" $ctx }}
  namespace: {{ $ns }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
type: Opaque
data:
  alertmanager.yaml: {{ toYaml $app.config | b64enc }}
  {{- range $key, $value := $app.templates }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- with $app.webConfig }}
  webconfig.yaml: {{ toYaml . | b64enc }}
  {{- end }}
{{- end }}
