{{- if .Values.serviceAccount.create -}}
{{- $names := list }}
{{- $ctxs := list (dict "helm" . "appKey" "server" "kindOverride" "vmalert") }}
{{- if .Values.alertmanager.enabled }}
  {{- $ctxs = append $ctxs (dict "helm" . "appKey" "alertmanager" "kindOverride" "vmalertmanager") }}
{{- end }}
{{- range $ctx := $ctxs }}
  {{- $names = append $names (include "vmalert.sa.name" $ctx) }}
{{- end }}
{{- $ctx := dict "helm" . }}
{{- $ns := include "vm.namespace" $ctx }}
{{- range $name := uniq $names }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $ns }}
  labels: {{ include "vm.metaLabels" $ctx | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}
