{{- $ctx := dict "helm" . "kindOverride" "vlagent-collector" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vm.plain.fullname" $ctx }}
  namespace: {{ include "vm.namespace" . }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
