## override to prevent objects name collision
global:
  license:
    keyRef:
      name: keyName
      key: key
grafana:
  serviceAccount:
    create: false
fullnameOverride: test
victoria-metrics-operator:
  fullnameOverride: "vm-operator"
vlsingle:
  enabled: false
vlcluster:
  enabled: true
  ingress:
    vlinsert:
      enabled: true
    vlselect:
      enabled: true
    vlstorage:
      enabled: true
