
{{- $Values := (.helm).Values | default .Values }}
{{- $runbookUrl := ($Values.defaultRules).runbookUrl | default "https://runbooks.prometheus-operator.dev/runbooks" }}
{{- $clusterLabel := ($Values.global).clusterLabel | default "cluster" }}
{{- $additionalGroupByLabels := append $Values.defaultRules.additionalGroupByLabels $clusterLabel }}
{{- $groupLabels := join "," (uniq $additionalGroupByLabels) }}
{{- $grafanaAddr := include "vm-k8s-stack.grafana.addr" . }}
name: vlagent
rules:
- alert: PersistentQueueIsDroppingData
  expr: sum(increase(vm_persistentqueue_bytes_dropped_total[5m])) without(path) > 0
  annotations:
    description: vlagent dropped {{`{{`}} $value | humanize1024 {{`}}`}} from persistent queue on instance {{`{{`}} $labels.instance {{`}}`}} for the last 10m.
    summary: Instance {{`{{`}} $labels.instance {{`}}`}} is dropping data from persistent queue
  condition: true
  for: 10m
  labels:
    severity: critical
- alert: RejectedRemoteWriteDataBlocksAreDropped
  expr: sum(increase(vlagent_remotewrite_packets_dropped_total[5m])) without(url) > 0
  annotations:
    description: Job "{{`{{`}} $labels.job {{`}}`}}" on instance {{`{{`}} $labels.instance {{`}}`}} drops the rejected by remote-write server data blocks. Check the logs to find the reason for rejects.
    summary: vlagent is dropping data blocks that are rejected by remote storage
  condition: true
  for: 15m
  labels:
    severity: warning
- alert: TooManyRemoteWriteErrors
  expr: rate(vlagent_remotewrite_retries_count_total[5m]) > 0
  annotations:
    description: |-
      vlagent fails to push data via remote write protocol to destination "{{`{{`}} $labels.url {{`}}`}}"
       Ensure that destination is up and reachable.
    summary: Job "{{`{{`}} $labels.job {{`}}`}}" on instance {{`{{`}} $labels.instance {{`}}`}} fails to push to remote storage
  condition: true
  for: 15m
  labels:
    severity: warning
- alert: RemoteWriteConnectionIsSaturated
  expr: (rate(vlagent_remotewrite_send_duration_seconds_total[5m]) / vlagent_remotewrite_queues) > 0.9
  annotations:
    description: |-
      The remote write connection between vlagent "{{`{{`}} $labels.job {{`}}`}}" (instance {{`{{`}} $labels.instance {{`}}`}}) and destination "{{`{{`}} $labels.url {{`}}`}}" is saturated by more than 90% and vlagent won't be able to keep up.
       There could be the following reasons for this:
       * vlagent can't send data fast enough through the existing network connections. Increase `-remoteWrite.queues` cmd-line flag value to establish more connections per destination.
       * remote destination can't accept data fast enough. Check if remote destination has enough resources for processing.
    summary: Remote write connection from "{{`{{`}} $labels.job {{`}}`}}" (instance {{`{{`}} $labels.instance {{`}}`}}) to {{`{{`}} $labels.url {{`}}`}} is saturated
  condition: true
  for: 15m
  labels:
    severity: warning
- alert: PersistentQueueForWritesIsSaturated
  expr: rate(vm_persistentqueue_write_duration_seconds_total[5m]) > 0.9
  annotations:
    description: Persistent queue writes for vlagent "{{`{{`}} $labels.job {{`}}`}}" (instance {{`{{`}} $labels.instance {{`}}`}}) are saturated by more than 90% and vlagent won't be able to keep up with flushing data on disk. In this case, consider to decrease load on the vlagent or improve the disk throughput.
    summary: Persistent queue writes for instance {{`{{`}} $labels.instance {{`}}`}} are saturated
  condition: true
  for: 15m
  labels:
    severity: warning
- alert: PersistentQueueForReadsIsSaturated
  expr: rate(vm_persistentqueue_read_duration_seconds_total[5m]) > 0.9
  annotations:
    description: Persistent queue reads for vlagent "{{`{{`}} $labels.job {{`}}`}}" (instance {{`{{`}} $labels.instance {{`}}`}}) are saturated by more than 90% and vlagent won't be able to keep up with reading data from the disk. In this case, consider to decrease load on the vlagent or improve the disk throughput.
    summary: Persistent queue reads for instance {{`{{`}} $labels.instance {{`}}`}} are saturated
  condition: true
  for: 15m
  labels:
    severity: warning
- alert: RequestErrorsToAPI
  expr: increase(vl_http_errors_total[5m]) > 0
  annotations:
    description: Requests to path {{`{{`}} $labels.path {{`}}`}} are receiving errors. Please verify if clients are sending correct requests.
    summary: Too many errors served for path {{`{{`}} $labels.path {{`}}`}} (instance {{`{{`}} $labels.instance {{`}}`}})
  condition: true
  for: 15m
  labels:
    severity: warning
- alert: RowsRejectedOnIngestion
  expr: rate(vl_rows_dropped_total[5m]) > 0
  annotations:
    description: 'VictoriaLogs is rejecting to ingest rows on "{{`{{`}} $labels.instance {{`}}`}}" due to the following reason: "{{`{{`}} $labels.reason {{`}}`}}"'
    summary: Some rows are rejected on "{{`{{`}} $labels.instance {{`}}`}}" on ingestion attempt
  condition: true
  for: 15m
  labels:
    severity: warning
condition: true
