{{- if .Values.serviceAccount.create -}}
{{- $ctx := dict "helm" . "kindOverride" "vlmcp" }}
{{- $fullname := include "vm.plain.fullname" $ctx }}
{{- $ns := include "vm.namespace" $ctx }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ tpl ((.Values.serviceAccount).name | default $fullname) $ctx }}
  namespace: {{ $ns }}
  {{- $_ := set $ctx "extraLabels" .Values.serviceAccount.extraLabels }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  {{- $_ := unset $ctx "extraLabels" }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
