apiVersion: v2
name: victoria-logs-mcp
description: A Helm chart for VictoriaLogs MCP server
type: application
version: 0.1.0
appVersion: v1.9.0
sources:
  - https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
kubeVersion: ">=1.25.0-0"
home: https://github.com/VictoriaMetrics/helm-charts
keywords:
  - victorialogs
  - logs
  - kubernetes
  - observability
  - mcp
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: "monitoring-logging"
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-logs-mcp
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
dependencies:
  - name: victoria-metrics-common
    version: "0.1.*"
    repository: oci://ghcr.io/victoriametrics/helm-charts
