apiVersion: v2
type: application
name: victoria-metrics-estimator
description: A Helm chart for VictoriaMetrics vmestimator
version: 0.0.0
# renovate: image=victoriametrics/vmestimator
appVersion: v0.1.15
sources:
  - https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
kubeVersion: ">=1.25.0-0"
home: https://github.com/VictoriaMetrics/helm-charts
maintainers:
  - name: VictoriaMetrics
    url: https://github.com/VictoriaMetrics
keywords:
  - victoriametrics
  - vmestimator
  - cardinality
  - kubernetes
  - observability
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: "monitoring-logging"
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-estimator
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/victoriametrics/vmestimator/
    - name: Changelog
      url: https://docs.victoriametrics.com/helm/victoria-metrics-estimator/changelog/
    - name: App Changelog
      url: https://docs.victoriametrics.com/victoriametrics/vmestimator/changelog/
dependencies:
  - name: victoria-metrics-common
    version: "0.3.*"
    repository: oci://ghcr.io/victoriametrics/helm-charts
