{{- $service := .Values.service }}
{{- if $service.enabled -}}
{{- $ctx := dict "helm" . }}
{{- $fullname := include "vm.plain.fullname" $ctx }}
{{- $ns := include "vm.namespace" $ctx }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vm.fullname" $ctx }}
  namespace: {{ include "vm.namespace" $ctx }}
  {{- with $service.annotations }}
  annotations: {{ toYaml . | nindent 4}}
  {{- end }}
  {{- $_ := set $ctx "extraLabels" $service.extraLabels }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  {{- $_ := unset $ctx "extraLabels" }}
spec:
  {{- with $service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with $service.externalIPs }}
  externalIPs: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml . | nindent 4 }}
  {{- end }}
  type: {{ $service.type }}
  {{- with $service.healthCheckNodePort }}
  healthCheckNodePort: {{ . }}
  {{- end }}
  {{- with $service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilies }}
  ipFamilies: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $service.trafficDistribution }}
  trafficDistribution: {{ . }}
  {{- end }}
  ports:
    {{- $extraArgs := .Values.extraArgs | default dict }}
    {{- $httpAddr := $extraArgs.httpListenAddr -}}
    {{- range ternary .Values.http (list (dict "name" "http" "value" $httpAddr "primary" true)) (empty $httpAddr) }}
    - name: {{ .name }}
      {{- $port := include "vm.port.from.flag" (dict "flag" .value "default" "9429") }}
      port: {{ ternary ($service.servicePort | default $port) $port (and .primary (not (empty $service.servicePort))) }}
      protocol: TCP
      targetPort: {{ .name }}
      {{- if and .primary $service.nodePort }}
      nodePort: {{ $service.nodePort }}
      {{- end }}
    {{- end }}
    {{- $syslogTCPAddr := index $extraArgs "syslog.listenAddr.tcp" -}}
    {{- range ternary .Values.syslog.tcp (list (dict "name" "syslog-tcp" "value" $syslogTCPAddr)) (empty $syslogTCPAddr) }}
    - name: {{ .name }}
      port: {{ include "vm.port.from.flag" (dict "flag" .value) }}
      protocol: TCP
      targetPort: {{ .name }}
    {{- end }}
    {{- $syslogUDPAddr := index $extraArgs "syslog.listenAddr.udp" -}}
    {{- range ternary .Values.syslog.udp (list (dict "name" "syslog-udp" "value" $syslogUDPAddr)) (empty $syslogUDPAddr) }}
    - name: {{ .name }}
      port: {{ include "vm.port.from.flag" (dict "flag" .value) }}
      protocol: UDP
      targetPort: {{ .name }}
    {{- end }}
    {{- range $service.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol | default "TCP" }}
      targetPort: {{ .targetPort }}
    {{- end }}
  {{- $_ := set $ctx "extraLabels" (mergeOverwrite (deepCopy (.Values.selectorLabels | default dict)) (deepCopy $service.selectorLabels)) }}
  selector: {{ include "vm.selectorLabels" $ctx | nindent 4 }}
  {{- $_ := unset $ctx "extraLabels" }}
{{- end }}
