{{- if and .Values.serviceAccount.create (not (include "vm.operator.enabled" .)) -}}
{{- $ctx := dict "helm" . "kindOverride" "vlagent" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vlagent.sa.name" . }}
  namespace: {{ include "vm.namespace" $ctx }}
  {{- $_ := set $ctx "extraLabels" .Values.serviceAccount.extraLabels }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
