
{{- $Values := (.helm).Values | default .Values }}
{{- $runbookUrl := ($Values.defaultRules).runbookUrl | default "https://runbooks.prometheus-operator.dev/runbooks" }}
{{- $additionalGroupByLabels := append $Values.defaultRules.additionalGroupByLabels "cluster" }}
{{- $groupLabels := join "," (uniq $additionalGroupByLabels) }}
{{- $grafanaAddr := include "vm-k8s-stack.grafana.addr" . }}
type: prometheus
name: alertmanager.rules
rules:
- alert: AlertmanagerFailedReload
  expr: max_over_time(alertmanager_config_last_reload_successful{job="{{ include \"vm-k8s-stack.alertmanager.name\"
    . }}",namespace="monitoring"}[5m]) == 0
  for: 10m0s
  labels:
    severity: critical
  annotations:
    description: Configuration has failed to load for {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.pod{{`}}`}}.
    runbook_url: {{ $runbookUrl }}/alertmanager/alertmanagerfailedreload'
    summary: Reloading an Alertmanager configuration has failed.
  condition: {{ true }}
- alert: AlertmanagerMembersInconsistent
  expr: max_over_time(alertmanager_cluster_members{job="{{ include \"vm-k8s-stack.alertmanager.name\"
    . }}",namespace="monitoring"}[5m]) < on(namespace,service) group_left() count(max_over_time(alertmanager_cluster_members{job="{{
    include \"vm-k8s-stack.alertmanager.name\" . }}",namespace="monitoring"}[5m]))
    by(namespace,service,\[\[\ \$groupLabels\ \]\])
  for: 15m0s
  labels:
    severity: critical
  annotations:
    description: Alertmanager {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.pod{{`}}`}} has only found
      {{`{{`}} $value {{`}}`}} members of the {{`{{`}}$labels.job{{`}}`}} cluster.
    runbook_url: {{ $runbookUrl }}/alertmanager/alertmanagermembersinconsistent'
    summary: A member of an Alertmanager cluster has not found all other cluster members.
  condition: {{ true }}
- alert: AlertmanagerFailedToSendAlerts
  expr: (rate(alertmanager_notifications_failed_total{job="{{ include \"vm-k8s-stack.alertmanager.name\"
    . }}",namespace="monitoring"}[15m]) / ignoring(reason) group_left() rate(alertmanager_notifications_total{job="{{
    include \"vm-k8s-stack.alertmanager.name\" . }}",namespace="monitoring"}[15m]))
    > 0.01
  for: 5m0s
  labels:
    severity: warning
  annotations:
    description: Alertmanager {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.pod{{`}}`}} failed to send
      {{`{{`}} $value | humanizePercentage {{`}}`}} of notifications to {{`{{`}} $labels.integration
      {{`}}`}}.
    runbook_url: {{ $runbookUrl }}/alertmanager/alertmanagerfailedtosendalerts'
    summary: An Alertmanager instance failed to send notifications.
  condition: {{ true }}
- alert: AlertmanagerClusterFailedToSendAlerts
  expr: min(rate(alertmanager_notifications_failed_total{job="{{ include \"vm-k8s-stack.alertmanager.name\"
    . }}",namespace="monitoring",integration=~".*"}[15m]) / ignoring(reason) group_left()
    rate(alertmanager_notifications_total{job="{{ include \"vm-k8s-stack.alertmanager.name\"
    . }}",namespace="monitoring",integration=~".*"}[15m])) by(namespace,service,integration,\[\[\
    \$groupLabels\ \]\]) > 0.01
  for: 5m0s
  labels:
    severity: critical
  annotations:
    description: The minimum notification failure rate to {{`{{`}} $labels.integration {{`}}`}}
      sent from any instance in the {{`{{`}}$labels.job{{`}}`}} cluster is {{`{{`}} $value | humanizePercentage
      {{`}}`}}.
    runbook_url: {{ $runbookUrl }}/alertmanager/alertmanagerclusterfailedtosendalerts'
    summary: All Alertmanager instances in a cluster failed to send notifications
      to a critical integration.
  condition: {{ true }}
- alert: AlertmanagerClusterFailedToSendAlerts
  expr: min(rate(alertmanager_notifications_failed_total{job="{{ include \"vm-k8s-stack.alertmanager.name\"
    . }}",namespace="monitoring",integration!~".*"}[15m]) / ignoring(reason) group_left()
    rate(alertmanager_notifications_total{job="{{ include \"vm-k8s-stack.alertmanager.name\"
    . }}",namespace="monitoring",integration!~".*"}[15m])) by(namespace,service,integration,\[\[\
    \$groupLabels\ \]\]) > 0.01
  for: 5m0s
  labels:
    severity: warning
  annotations:
    description: The minimum notification failure rate to {{`{{`}} $labels.integration {{`}}`}}
      sent from any instance in the {{`{{`}}$labels.job{{`}}`}} cluster is {{`{{`}} $value | humanizePercentage
      {{`}}`}}.
    runbook_url: {{ $runbookUrl }}/alertmanager/alertmanagerclusterfailedtosendalerts'
    summary: All Alertmanager instances in a cluster failed to send notifications
      to a non-critical integration.
  condition: {{ true }}
- alert: AlertmanagerConfigInconsistent
  expr: count(count_values("config_hash", alertmanager_config_hash{job="{{ include
    \"vm-k8s-stack.alertmanager.name\" . }}",namespace="monitoring"}) by(namespace,service,\[\[\
    \$groupLabels\ \]\])) by(namespace,service,\[\[\ \$groupLabels\ \]\]) != 1
  for: 20m0s
  labels:
    severity: critical
  annotations:
    description: Alertmanager instances within the {{`{{`}}$labels.job{{`}}`}} cluster have different
      configurations.
    runbook_url: {{ $runbookUrl }}/alertmanager/alertmanagerconfiginconsistent'
    summary: Alertmanager instances within the same cluster have different configurations.
  condition: {{ true }}
- alert: AlertmanagerClusterDown
  expr: (count(avg_over_time(up{job="{{ include \"vm-k8s-stack.alertmanager.name\"
    . }}",namespace="monitoring"}[5m]) < 0.5) by(namespace,service,\[\[\ \$groupLabels\
    \]\]) / count(up{job="{{ include \"vm-k8s-stack.alertmanager.name\" . }}",namespace="monitoring"})
    by(namespace,service,\[\[\ \$groupLabels\ \]\])) >= 0.5
  for: 5m0s
  labels:
    severity: critical
  annotations:
    description: '{{`{{`}} $value | humanizePercentage {{`}}`}} of Alertmanager instances within
      the {{`{{`}}$labels.job{{`}}`}} cluster have been up for less than half of the last 5m.'
    runbook_url: {{ $runbookUrl }}/alertmanager/alertmanagerclusterdown'
    summary: Half or more of the Alertmanager instances within the same cluster are
      down.
  condition: {{ true }}
- alert: AlertmanagerClusterCrashlooping
  expr: (count(changes(process_start_time_seconds{job="{{ include \"vm-k8s-stack.alertmanager.name\"
    . }}",namespace="monitoring"}[10m]) > 4) by(namespace,service,\[\[\ \$groupLabels\
    \]\]) / count(up{job="{{ include \"vm-k8s-stack.alertmanager.name\" . }}",namespace="monitoring"})
    by(namespace,service,\[\[\ \$groupLabels\ \]\])) >= 0.5
  for: 5m0s
  labels:
    severity: critical
  annotations:
    description: '{{`{{`}} $value | humanizePercentage {{`}}`}} of Alertmanager instances within
      the {{`{{`}}$labels.job{{`}}`}} cluster have restarted at least 5 times in the last 10m.'
    runbook_url: {{ $runbookUrl }}/alertmanager/alertmanagerclustercrashlooping'
    summary: Half or more of the Alertmanager instances within the same cluster are
      crashlooping.
  condition: {{ true }}
condition: {{ ($Values.alertmanager).enabled }}
