
{{- $Values := (.helm).Values | default .Values }}
{{- $runbookUrl := ($Values.defaultRules).runbookUrl | default "https://runbooks.prometheus-operator.dev/runbooks" }}
{{- $additionalGroupByLabels := append $Values.defaultRules.additionalGroupByLabels "cluster" }}
{{- $groupLabels := join "," (uniq $additionalGroupByLabels) }}
{{- $grafanaAddr := include "vm-k8s-stack.grafana.addr" . }}
type: prometheus
name: k8s.rules.pod_owner
rules:
- record: namespace_workload_pod:kube_pod_owner:relabel
  expr: max(label_replace(label_replace(kube_pod_owner{job="kube-state-metrics",owner_kind="ReplicaSet"},
    "replicaset", "$1", "owner_name", "(.*)") * on(cluster,replicaset,namespace) group_left(owner_name)
    topk(1, max(kube_replicaset_owner{job="kube-state-metrics",owner_kind=""}) by(\[\[\
    \$groupLabels\ \]\],replicaset,namespace,owner_name)) by(\[\[\ \$groupLabels\
    \]\],replicaset,namespace), "workload", "$1", "replicaset", "(.*)")) by(\[\[\
    \$groupLabels\ \]\],namespace,workload,pod)
  labels:
    workload_type: replicaset
  condition: {{ true }}
- record: namespace_workload_pod:kube_pod_owner:relabel
  expr: max(label_replace(label_replace(kube_pod_owner{job="kube-state-metrics",owner_kind="ReplicaSet"},
    "replicaset", "$1", "owner_name", "(.*)") * on(replicaset,namespace,cluster) group_left(owner_name)
    topk(1, max(kube_replicaset_owner{job="kube-state-metrics",owner_kind="Deployment"})
    by(\[\[\ \$groupLabels\ \]\],replicaset,namespace,owner_name)) by(\[\[\ \$groupLabels\
    \]\],replicaset,namespace), "workload", "$1", "owner_name", "(.*)")) by(\[\[\
    \$groupLabels\ \]\],namespace,workload,pod)
  labels:
    workload_type: deployment
  condition: {{ true }}
- record: namespace_workload_pod:kube_pod_owner:relabel
  expr: max(label_replace(kube_pod_owner{job="kube-state-metrics",owner_kind="DaemonSet"},
    "workload", "$1", "owner_name", "(.*)")) by(\[\[\ \$groupLabels\ \]\],namespace,workload,pod)
  labels:
    workload_type: daemonset
  condition: {{ true }}
- record: namespace_workload_pod:kube_pod_owner:relabel
  expr: max(label_replace(kube_pod_owner{job="kube-state-metrics",owner_kind="StatefulSet"},
    "workload", "$1", "owner_name", "(.*)")) by(\[\[\ \$groupLabels\ \]\],namespace,workload,pod)
  labels:
    workload_type: statefulset
  condition: {{ true }}
- record: namespace_workload_pod:kube_pod_owner:relabel
  expr: group(label_join(group(label_join(kube_pod_owner{job="kube-state-metrics",owner_kind="Job"},
    "job_name", "", "owner_name")) by(\[\[\ \$groupLabels\ \]\],namespace,job_name,pod,owner_name)
    * on(cluster,namespace,job_name) group_left() group(kube_job_owner{job="kube-state-metrics",owner_kind=~"Pod|"})
    by(\[\[\ \$groupLabels\ \]\],namespace,job_name), "workload", "", "owner_name"))
    by(\[\[\ \$groupLabels\ \]\],namespace,workload,pod)
  labels:
    workload_type: job
  condition: {{ true }}
- record: namespace_workload_pod:kube_pod_owner:relabel
  expr: max(label_replace(kube_pod_owner{job="kube-state-metrics",owner_kind="",owner_name=""},
    "workload", "$1", "pod", "(.+)")) by(\[\[\ \$groupLabels\ \]\],namespace,workload,pod)
  labels:
    workload_type: barepod
  condition: {{ true }}
- record: namespace_workload_pod:kube_pod_owner:relabel
  expr: max(label_replace(kube_pod_owner{job="kube-state-metrics",owner_kind="Node"},
    "workload", "$1", "pod", "(.+)")) by(\[\[\ \$groupLabels\ \]\],namespace,workload,pod)
  labels:
    workload_type: staticpod
  condition: {{ true }}
- record: namespace_workload_pod:kube_pod_owner:relabel
  expr: group(label_join(label_join(group(label_join(kube_pod_owner{job="kube-state-metrics",owner_kind="Job"},
    "job_name", "", "owner_name")) by(\[\[\ \$groupLabels\ \]\],namespace,job_name,pod)
    * on(cluster,namespace,job_name) group_left(owner_kind,owner_name) group(kube_job_owner{job="kube-state-metrics",owner_kind!="Pod",owner_kind!=""})
    by(\[\[\ \$groupLabels\ \]\],namespace,job_name,owner_kind,owner_name), "workload",
    "", "owner_name"), "workload_type", "", "owner_kind") or label_replace(label_replace(label_replace(kube_pod_owner{job="kube-state-metrics",owner_kind="ReplicaSet"},
    "replicaset", "$1", "owner_name", "(.+)") * on(cluster,namespace,replicaset) group_left(owner_kind,owner_name)
    group(kube_replicaset_owner{job="kube-state-metrics",owner_kind!="Deployment",owner_kind!=""})
    by(\[\[\ \$groupLabels\ \]\],namespace,replicaset,owner_kind,owner_name), "workload",
    "$1", "owner_name", "(.+)") or label_replace(group(kube_pod_owner{job="kube-state-metrics",owner_kind!="ReplicaSet",owner_kind!="DaemonSet",owner_kind!="StatefulSet",owner_kind!="Job",owner_kind!="Node",owner_kind!=""})
    by(\[\[\ \$groupLabels\ \]\],namespace,pod,owner_name,owner_kind), "workload",
    "$1", "owner_name", "(.+)"), "workload_type", "$1", "owner_kind", "(.+)")) by(\[\[\
    \$groupLabels\ \]\],namespace,workload,workload_type,pod)
  condition: {{ true }}
condition: {{ true }}
