
{{- $Values := (.helm).Values | default .Values }}
{{- $runbookUrl := ($Values.defaultRules).runbookUrl | default "https://runbooks.prometheus-operator.dev/runbooks" }}
{{- $additionalGroupByLabels := append $Values.defaultRules.additionalGroupByLabels "cluster" }}
{{- $groupLabels := join "," (uniq $additionalGroupByLabels) }}
{{- $grafanaAddr := include "vm-k8s-stack.grafana.addr" . }}
type: prometheus
name: kube-apiserver-histogram.rules
rules:
- record: cluster_quantile:apiserver_request_sli_duration_seconds:histogram_quantile
  expr: histogram_quantile(0.99, sum(rate(apiserver_request_sli_duration_seconds_bucket{job="apiserver",verb=~"LIST|GET",subresource!~"proxy|attach|log|exec|portforward"}[5m]))
    by(\[\[\ \$groupLabels\ \]\],le,resource)) > 0
  labels:
    quantile: "0.99"
    verb: read
  condition: {{ true }}
- record: cluster_quantile:apiserver_request_sli_duration_seconds:histogram_quantile
  expr: histogram_quantile(0.99, sum(rate(apiserver_request_sli_duration_seconds_bucket{job="apiserver",verb=~"POST|PUT|PATCH|DELETE",subresource!~"proxy|attach|log|exec|portforward"}[5m]))
    by(\[\[\ \$groupLabels\ \]\],le,resource)) > 0
  labels:
    quantile: "0.99"
    verb: write
  condition: {{ true }}
condition: {{ ($Values.kubeApiServer).enabled }}
