
{{- $Values := (.helm).Values | default .Values }}
{{- $runbookUrl := ($Values.defaultRules).runbookUrl | default "https://runbooks.prometheus-operator.dev/runbooks" }}
{{- $additionalGroupByLabels := append $Values.defaultRules.additionalGroupByLabels "cluster" }}
{{- $groupLabels := join "," (uniq $additionalGroupByLabels) }}
{{- $grafanaAddr := include "vm-k8s-stack.grafana.addr" . }}
type: prometheus
name: kube-apiserver-availability.rules
interval: 3m0s
rules:
- record: code_verb:apiserver_request_total:increase30d
  expr: (avg_over_time(code_verb:apiserver_request_total:increase1h[30d]) * 24) *
    30
  condition: {{ true }}
- record: code:apiserver_request_total:increase30d
  expr: sum(code_verb:apiserver_request_total:increase30d{verb=~"LIST|GET"}) by(\[\[\
    \$groupLabels\ \]\],code)
  labels:
    verb: read
  condition: {{ true }}
- record: code:apiserver_request_total:increase30d
  expr: sum(code_verb:apiserver_request_total:increase30d{verb=~"POST|PUT|PATCH|DELETE"})
    by(\[\[\ \$groupLabels\ \]\],code)
  labels:
    verb: write
  condition: {{ true }}
- record: cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase1h
  expr: sum(increase(apiserver_request_sli_duration_seconds_bucket[1h])) by(\[\[\
    \$groupLabels\ \]\],verb,scope,le)
  condition: {{ true }}
- record: cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d
  expr: sum((avg_over_time(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase1h[30d])
    * 24) * 30) by(\[\[\ \$groupLabels\ \]\],verb,scope,le)
  condition: {{ true }}
- record: cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase1h
  expr: sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase1h{le="+Inf"})
    by(\[\[\ \$groupLabels\ \]\],verb,scope)
  condition: {{ true }}
- record: cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d
  expr: sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{le="+Inf"})
    by(\[\[\ \$groupLabels\ \]\],verb,scope)
  condition: {{ true }}
- record: apiserver_request:availability30d
  expr: 1 - ((((sum(cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d{verb=~"POST|PUT|PATCH|DELETE"})
    by(\[\[\ \$groupLabels\ \]\]) - sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"POST|PUT|PATCH|DELETE",le=~"1(\\.0)?"}
    or vector(0)) by(\[\[\ \$groupLabels\ \]\])) + (sum(cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d{verb=~"LIST|GET"})
    by(\[\[\ \$groupLabels\ \]\]) - ((sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope=~"resource|",le=~"1(\\.0)?"}
    or vector(0)) by(\[\[\ \$groupLabels\ \]\]) + sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope="namespace",le=~"5(\\.0)?"}
    or vector(0)) by(\[\[\ \$groupLabels\ \]\])) + sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope="cluster",le=~"30(\\.0)?"}
    or vector(0)) by(\[\[\ \$groupLabels\ \]\])))) + sum(code:apiserver_request_total:increase30d{code=~"5.."}
    or vector(0)) by(\[\[\ \$groupLabels\ \]\])) / sum(code:apiserver_request_total:increase30d)
    by(\[\[\ \$groupLabels\ \]\]))
  labels:
    verb: all
  condition: {{ true }}
- record: apiserver_request:availability30d
  expr: 1 - (((sum(cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d{verb=~"LIST|GET"})
    by(\[\[\ \$groupLabels\ \]\]) - ((sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope=~"resource|",le=~"1(\\.0)?"}
    or vector(0)) by(\[\[\ \$groupLabels\ \]\]) + sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope="namespace",le=~"5(\\.0)?"}
    or vector(0)) by(\[\[\ \$groupLabels\ \]\])) + sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope="cluster",le=~"30(\\.0)?"}
    or vector(0)) by(\[\[\ \$groupLabels\ \]\]))) + sum(code:apiserver_request_total:increase30d{verb="read",code=~"5.."}
    or vector(0)) by(\[\[\ \$groupLabels\ \]\])) / sum(code:apiserver_request_total:increase30d{verb="read"})
    by(\[\[\ \$groupLabels\ \]\]))
  labels:
    verb: read
  condition: {{ true }}
- record: apiserver_request:availability30d
  expr: 1 - (((sum(cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d{verb=~"POST|PUT|PATCH|DELETE"})
    by(\[\[\ \$groupLabels\ \]\]) - sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"POST|PUT|PATCH|DELETE",le=~"1(\\.0)?"}
    or vector(0)) by(\[\[\ \$groupLabels\ \]\])) + sum(code:apiserver_request_total:increase30d{verb="write",code=~"5.."}
    or vector(0)) by(\[\[\ \$groupLabels\ \]\])) / sum(code:apiserver_request_total:increase30d{verb="write"})
    by(\[\[\ \$groupLabels\ \]\]))
  labels:
    verb: write
  condition: {{ true }}
- record: code_resource:apiserver_request_total:rate5m
  expr: sum(rate(apiserver_request_total{job="apiserver",verb=~"LIST|GET"}[5m])) by(\[\[\
    \$groupLabels\ \]\],code,resource)
  labels:
    verb: read
  condition: {{ true }}
- record: code_resource:apiserver_request_total:rate5m
  expr: sum(rate(apiserver_request_total{job="apiserver",verb=~"POST|PUT|PATCH|DELETE"}[5m]))
    by(\[\[\ \$groupLabels\ \]\],code,resource)
  labels:
    verb: write
  condition: {{ true }}
- record: code_verb:apiserver_request_total:increase1h
  expr: sum(increase(apiserver_request_total{job="apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE",code=~"2.."}[1h]))
    by(\[\[\ \$groupLabels\ \]\],code,verb)
  condition: {{ true }}
- record: code_verb:apiserver_request_total:increase1h
  expr: sum(increase(apiserver_request_total{job="apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE",code=~"3.."}[1h]))
    by(\[\[\ \$groupLabels\ \]\],code,verb)
  condition: {{ true }}
- record: code_verb:apiserver_request_total:increase1h
  expr: sum(increase(apiserver_request_total{job="apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE",code=~"4.."}[1h]))
    by(\[\[\ \$groupLabels\ \]\],code,verb)
  condition: {{ true }}
- record: code_verb:apiserver_request_total:increase1h
  expr: sum(increase(apiserver_request_total{job="apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE",code=~"5.."}[1h]))
    by(\[\[\ \$groupLabels\ \]\],code,verb)
  condition: {{ true }}
condition: {{ ($Values.kubeApiServer).enabled }}
