
{{- $Values := (.helm).Values | default .Values }}
{{- $runbookUrl := ($Values.defaultRules).runbookUrl | default "https://runbooks.prometheus-operator.dev/runbooks" }}
{{- $additionalGroupByLabels := append $Values.defaultRules.additionalGroupByLabels "cluster" }}
{{- $groupLabels := join "," (uniq $additionalGroupByLabels) }}
{{- $grafanaAddr := include "vm-k8s-stack.grafana.addr" . }}
type: prometheus
name: kubelet.rules
rules:
- record: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile
  expr: histogram_quantile(0.99, sum(rate(kubelet_pleg_relist_duration_seconds_bucket{job="kubelet",metrics_path="/metrics"}[5m]))
    by(\[\[\ \$groupLabels\ \]\],instance,le) * on(cluster,instance) group_left(node)
    max(kubelet_node_name{job="kubelet",metrics_path="/metrics"}) by(\[\[\ \$groupLabels\
    \]\],instance,node))
  labels:
    quantile: "0.99"
  condition: {{ true }}
- record: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile
  expr: histogram_quantile(0.9, sum(rate(kubelet_pleg_relist_duration_seconds_bucket{job="kubelet",metrics_path="/metrics"}[5m]))
    by(\[\[\ \$groupLabels\ \]\],instance,le) * on(cluster,instance) group_left(node)
    max(kubelet_node_name{job="kubelet",metrics_path="/metrics"}) by(\[\[\ \$groupLabels\
    \]\],instance,node))
  labels:
    quantile: "0.9"
  condition: {{ true }}
- record: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile
  expr: histogram_quantile(0.5, sum(rate(kubelet_pleg_relist_duration_seconds_bucket{job="kubelet",metrics_path="/metrics"}[5m]))
    by(\[\[\ \$groupLabels\ \]\],instance,le) * on(cluster,instance) group_left(node)
    max(kubelet_node_name{job="kubelet",metrics_path="/metrics"}) by(\[\[\ \$groupLabels\
    \]\],instance,node))
  labels:
    quantile: "0.5"
  condition: {{ true }}
condition: {{ ($Values.kubelet).enabled }}
