
{{- $Values := (.helm).Values | default .Values }}
{{- $runbookUrl := ($Values.defaultRules).runbookUrl | default "https://runbooks.prometheus-operator.dev/runbooks" }}
{{- $additionalGroupByLabels := append $Values.defaultRules.additionalGroupByLabels "cluster" }}
{{- $groupLabels := join "," (uniq $additionalGroupByLabels) }}
{{- $grafanaAddr := include "vm-k8s-stack.grafana.addr" . }}
type: prometheus
name: kube-prometheus-general.rules
rules:
- record: count:up1
  expr: count(up == 1) without(instance,pod,node)
  condition: {{ true }}
- record: count:up0
  expr: count(up == 0) without(instance,pod,node)
  condition: {{ true }}
condition: {{ true }}
