
{{- $Values := (.helm).Values | default .Values }}
{{- $runbookUrl := ($Values.defaultRules).runbookUrl | default "https://runbooks.prometheus-operator.dev/runbooks" }}
{{- $additionalGroupByLabels := append $Values.defaultRules.additionalGroupByLabels "cluster" }}
{{- $groupLabels := join "," (uniq $additionalGroupByLabels) }}
{{- $grafanaAddr := include "vm-k8s-stack.grafana.addr" . }}
type: prometheus
name: kube-apiserver-slos
rules:
- alert: KubeAPIErrorBudgetBurn
  expr: (sum(apiserver_request:burnrate1h) by(\[\[\ \$groupLabels\ \]\]) > 0.14400000000000002)
    and on(cluster) (sum(apiserver_request:burnrate5m) by(\[\[\ \$groupLabels\ \]\])
    > 0.14400000000000002)
  for: 2m0s
  labels:
    long: 1h
    severity: critical
    short: 5m
  annotations:
    description: The API server is burning too much error budget on cluster {{`{{`}} $labels.cluster
      {{`}}`}}.
    runbook_url: {{ $runbookUrl }}/kubernetes/kubeapierrorbudgetburn'
    summary: The API server is burning too much error budget.
  condition: {{ true }}
- alert: KubeAPIErrorBudgetBurn
  expr: (sum(apiserver_request:burnrate6h) by(\[\[\ \$groupLabels\ \]\]) > 0.06) and
    on(cluster) (sum(apiserver_request:burnrate30m) by(\[\[\ \$groupLabels\ \]\])
    > 0.06)
  for: 15m0s
  labels:
    long: 6h
    severity: critical
    short: 30m
  annotations:
    description: The API server is burning too much error budget on cluster {{`{{`}} $labels.cluster
      {{`}}`}}.
    runbook_url: {{ $runbookUrl }}/kubernetes/kubeapierrorbudgetburn'
    summary: The API server is burning too much error budget.
  condition: {{ true }}
- alert: KubeAPIErrorBudgetBurn
  expr: (sum(apiserver_request:burnrate1d) by(\[\[\ \$groupLabels\ \]\]) > 0.03) and
    on(cluster) (sum(apiserver_request:burnrate2h) by(\[\[\ \$groupLabels\ \]\]) >
    0.03)
  for: 1h0m0s
  labels:
    long: 1d
    severity: warning
    short: 2h
  annotations:
    description: The API server is burning too much error budget on cluster {{`{{`}} $labels.cluster
      {{`}}`}}.
    runbook_url: {{ $runbookUrl }}/kubernetes/kubeapierrorbudgetburn'
    summary: The API server is burning too much error budget.
  condition: {{ true }}
- alert: KubeAPIErrorBudgetBurn
  expr: (sum(apiserver_request:burnrate3d) by(\[\[\ \$groupLabels\ \]\]) > 0.01) and
    on(cluster) (sum(apiserver_request:burnrate6h) by(\[\[\ \$groupLabels\ \]\]) >
    0.01)
  for: 3h0m0s
  labels:
    long: 3d
    severity: warning
    short: 6h
  annotations:
    description: The API server is burning too much error budget on cluster {{`{{`}} $labels.cluster
      {{`}}`}}.
    runbook_url: {{ $runbookUrl }}/kubernetes/kubeapierrorbudgetburn'
    summary: The API server is burning too much error budget.
  condition: {{ true }}
condition: {{ ($Values.kubeApiServer).enabled }}
