
{{- $Values := (.helm).Values | default .Values }}
{{- $runbookUrl := ($Values.defaultRules).runbookUrl | default "https://runbooks.prometheus-operator.dev/runbooks" }}
{{- $clusterLabel := ($Values.global).clusterLabel | default "cluster" }}
{{- $extraGroupByLabels := uniq (append .extraGroupByLabels $clusterLabel) }}
{{- $groupLabels := join "," $extraGroupByLabels }}
{{- $grafanaAddr := include "vm-k8s-stack.grafana.addr" . }}
name: kubernetes-system-scheduler
rules:
- alert: KubeSchedulerDown
  expr: absent(up{job="kube-scheduler"})
  annotations:
    description: KubeScheduler has disappeared from Prometheus target discovery.
    runbook_url: {{ $runbookUrl }}/kubernetes/kubeschedulerdown
    summary: Target disappeared from Prometheus target discovery.
  condition: {{ ($Values.kubeScheduler).enabled }}
  for: 15m
  labels:
    severity: critical
- alert: KubeSchedulerInstanceUnreachable
  expr: up{job="kube-scheduler"} == 0
  annotations:
    description: A KubeScheduler instance has been unreachable for more than 15 minutes.
    runbook_url: {{ $runbookUrl }}/kubernetes/kubeschedulerinstanceunreachable
    summary: KubeScheduler instance is unreachable.
  condition: true
  for: 15m
  labels:
    severity: warning
condition: {{ ($Values.kubeScheduler).enabled }}
