
{{- $Values := (.helm).Values | default .Values }}
{{- $runbookUrl := ($Values.defaultRules).runbookUrl | default "https://runbooks.prometheus-operator.dev/runbooks" }}
{{- $additionalGroupByLabels := append $Values.defaultRules.additionalGroupByLabels "cluster" }}
{{- $groupLabels := join "," (uniq $additionalGroupByLabels) }}
{{- $grafanaAddr := include "vm-k8s-stack.grafana.addr" . }}
type: prometheus
name: node.rules
rules:
- record: 'node_namespace_pod:kube_pod_info:'
  expr: topk(1, max(label_replace(kube_pod_info{job="kube-state-metrics",node!=""},
    "pod", "$1", "pod", "(.*)")) by(\[\[\ \$groupLabels\ \]\],node,namespace,pod))
    by(\[\[\ \$groupLabels\ \]\],namespace,pod)
  condition: {{ true }}
- record: node:node_num_cpu:sum
  expr: count(node_cpu_seconds_total{mode="idle",job="{{ include \"vm-k8s-stack.nodeExporter.name\"
    . }}"} * on(cluster,namespace,pod) group_left(node) topk(1, node_namespace_pod:kube_pod_info:)
    by(\[\[\ \$groupLabels\ \]\],namespace,pod)) by(\[\[\ \$groupLabels\ \]\],node)
  condition: {{ true }}
- record: :node_memory_MemAvailable_bytes:sum
  expr: sum(node_memory_MemAvailable_bytes{job="{{ include \"vm-k8s-stack.nodeExporter.name\"
    . }}"} or (((node_memory_Buffers_bytes{job="{{ include \"vm-k8s-stack.nodeExporter.name\"
    . }}"} + node_memory_Cached_bytes{job="{{ include \"vm-k8s-stack.nodeExporter.name\"
    . }}"}) + node_memory_MemFree_bytes{job="{{ include \"vm-k8s-stack.nodeExporter.name\"
    . }}"}) + node_memory_Slab_bytes{job="{{ include \"vm-k8s-stack.nodeExporter.name\"
    . }}"})) by(\[\[\ \$groupLabels\ \]\])
  condition: {{ true }}
- record: node:node_cpu_utilization:ratio_rate5m
  expr: avg(sum(rate(node_cpu_seconds_total{mode!="idle",mode!="iowait",mode!="steal",job="{{
    include \"vm-k8s-stack.nodeExporter.name\" . }}"}[5m])) without(mode)) by(\[\[\
    \$groupLabels\ \]\],node)
  condition: {{ true }}
- record: cluster:node_cpu:ratio_rate5m
  expr: avg(node:node_cpu_utilization:ratio_rate5m) by(\[\[\ \$groupLabels\ \]\])
  condition: {{ true }}
condition: {{ true }}
