{{- if .Values.syncJob.enabled }}
{{- $ctx := dict "helm" . "appKey" "syncJob" }}
{{- $fullname := include "vm.fullname" $ctx }}
{{- $ns := include "vm.namespace" $ctx }}
{{- $job := .Values.syncJob }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullname }}-sync-job
  namespace: {{ $ns }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: {{ $job.ttlSecondsAfterFinished }}
  backoffLimit: {{ $job.backoffLimit }}
  template:
    metadata:
      labels: {{ include "vm.labels" $ctx | nindent 8 }}
      {{- with $job.podAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ $fullname }}-sync-job
      restartPolicy: OnFailure
      {{- with $job.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $job.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $job.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      containers:
        - name: sync-job
          image: "{{ $job.image.repository }}:{{ $job.image.tag }}"
          imagePullPolicy: {{ $job.image.pullPolicy }}
          env:
            {{- with $job.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RELEASE
              value: {{ include "vm.release" $ctx | quote }}
            - name: RESOURCE_PREFIX
              value: {{ $job.resourcePrefix | default (include "vm.fullname" $ctx) | quote }}
            - name: PRUNE
              value: {{ $job.prune | quote }}
            - name: OWNER_REFERENCES
              value: {{ $job.useOwnerReferences | quote }}
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          volumeMounts:
            - name: config
              mountPath: /etc/config
              readOnly: true
          {{- with $job.containerSecurityContext }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ $fullname }}-sync-job-config
      {{- with $job.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $job.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $job.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
