{{- if not .Values.config.existingConfigMap }}
{{- $ctx := dict "helm" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vmestimator.fullname" (dict "root" .) }}
  namespace: {{ include "vm.namespace" $ctx }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
data:
  {{ .Values.config.key }}: |
{{- toYaml .Values.config.data | nindent 4 }}
{{- end }}
