{{- $ctx := .Values.ctx | default dict -}}
{{- $_ := unset .Values "ctx" -}}
{{- range $k, $v := $ctx }}
  {{- $_ := set $ $k $v -}}
{{- end }}
vm:
  fqdn: {{ include "vm.fqdn" . }}
  url: {{ include "vm.url" . }}