{{- $ctx := dict "helm" . }}
{{- $fullname := include "vm.fullname" . }}
{{- $_ := set $ctx "fullname" $fullname }}
{{- $commonAuth := dict "spec" ((((.Values).common).vmauth).spec | default dict) }}
{{- $auth := mergeOverwrite (deepCopy $commonAuth) (deepCopy ((((.Values).read).global).vmauth | default dict)) }}

{{- $_ := set $ctx "style" "managed" }}
{{- $urls := default list }}
{{- $components := default list }}
{{- range $i, $z := $.Values.availabilityZones }}
  {{- $zone := mergeOverwrite (deepCopy $.Values.zoneTpl) $z }}
  {{- if (((($.Values).read).global).vmauth).enabled }}
    {{- if $zone.read.crossZone.vmauth.enabled -}}
      {{- $authSpec := ((($zone.read).crossZone).vmauth).spec | default dict }}
      {{- $_ := set $zone.read.crossZone.vmauth "spec" (mergeOverwrite (deepCopy $commonAuth.spec) $authSpec) }}
      {{- $_ := set $ctx "zone" $zone }}
      {{- $_ := set $ctx "appKey" (list "zone" "read" "crossZone" "vmauth" "spec") }}
      {{- $urls = append $urls (include "vm.url" $ctx) }}
    {{- end -}}
  {{- else -}}
    {{- if or $zone.read.crossZone.vmauth.enabled $zone.read.perZone.vmauth.enabled }}
      {{- fail "Neither cross zone nor per zone VMAuth are expected to be enabled, when global read balancer is disabled"}}
    {{- end }}
    {{- if $zone.vmcluster.enabled }}
      {{- $clusterName := tpl $zone.vmcluster.name (dict "zone" $z) }}
      {{- $components = append $components (printf "vmselect-%s" $clusterName) }}
    {{- else if $zone.vmsingle.enabled }}
      {{- $singleName := tpl $zone.vmsingle.name (dict "zone" $z) }}
      {{- $components = append $components (printf "vmsingle-%s" $singleName) }}
    {{- end -}}
  {{- end -}}
{{- end }}
{{- $_ := unset $ctx "style" }}

{{- $_ := set $ctx "appKey" (list "vmauth" "spec") }}
{{- $_ := set $ctx "fullname" $fullname }}
{{- $_ := set $ctx "vmauth" $auth }}

{{- if ((((.Values).read).global).vmauth).enabled }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: {{ include "vm.cr.fullname" $ctx }}
  namespace: {{ include "vm.namespace" $ctx }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  {{- with .Values.read.global.vmauth.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end  }}
spec:
  {{- with (omit $auth.spec "unauthorizedUserAccessSpec") }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  unauthorizedUserAccessSpec:
    url_map:
      - src_paths:
          - "/select/.+"
        load_balancing_policy: first_available
        {{- if empty $urls }}
          {{- fail "No global vmauth read backend urls defined" -}}
        {{- end }}
        url_prefix: {{ toYaml $urls | nindent 10 }}
{{- else -}}
{{- if empty $components }}
  {{- fail "Failed to setup global service. No clusters enabled" -}}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vm.cr.fullname" $ctx }}
  namespace: {{ include "vm.namespace" $ctx }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: {{ toJson $components }}
  ports:
    - protocol: TCP
      port: {{ $auth.spec.port }}
      targetPort: http
{{- end }}

