name: "Lint charts"

on:
  push:
    paths:
      - Makefile
      - 'charts/*/lint/**'
      - '.github/workflows/run-lint.yaml'
    branches:
      - master
  pull_request:
    paths:
      - Makefile
      - 'charts/*/lint/**'
      - '.github/workflows/run-lint.yaml'
    branches:
      - master

env:
  HELM_VERSION: 4.2.3

permissions: {}

jobs:
  lint-charts:
    name: Lint Charts
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Install helm
        uses: yokawasa/action-setup-kube-tools@b16d49b2c459d33cf9d4c300a220ef0bcdbc730a  # v0.14.0
        with:
          setup-tools: |
            helm
          helm: "${{ env.HELM_VERSION }}"

      - name: Install deps
        run: |
          make helm-plugins

      - name: Run lint
        run: |
          make lint

      - name: Run template
        run: |
          make template

      - name: Run unittest
        run: |
          make unittest
