name: "Lint charts"

on:
  push:
    paths:
      - Makefile
      - 'charts/*/lint/**'
      - '.github/workflows/run-lint.yaml'
    branches:
      - master
  pull_request:
    paths:
      - Makefile
      - 'charts/*/lint/**'
      - '.github/workflows/run-lint.yaml'
    branches:
      - master

env:
  HELM_VERSION: 4.1.1

permissions: {}

jobs:
  lint-charts:
    name: Lint Charts
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false

      - name: Install helm
        uses: yokawasa/action-setup-kube-tools@9d39563c24d4a419d1a8289c34d6da5a6171252c  # v0.13.5
        with:
          setup-tools: |
            helm
          helm: "${{ env.HELM_VERSION }}"

      - name: Install deps
        run: |
          make helm-plugins

      - name: Run lint
        run: |
          make lint

      - name: Run template
        run: |
          make template

      - name: Run unittest
        run: |
          make unittest
